### ISSUE TITLE
Resources / Collections can be added from any page

### ISSUE THREAD

**Issue by toobulkeh** [vaporware/parkland#2]
A QuickBooks Online-like giant "+" button at the top center navbar.

**Comment by toobulkeh** [comment]
<img width="749" alt="screen shot 2015-07-14 at 9 29 52 pm" src="https://cloud.githubusercontent.com/assets/1342064/8688911/84313b70-2a6f-11e5-8b9f-37c0536af44b.png">

**Comment by toobulkeh** [comment]
<img width="1847" alt="screen shot 2015-07-28 at 11 24 34 am" src="https://cloud.githubusercontent.com/assets/1342064/8935541/44054152-351b-11e5-83c6-603eaa0268e7.png">

**Comment by rjcox** [comment]
Resources and collections are now able to be added with "+" symbol on the right side of the header, application wide.
