### ISSUE TITLE
The home page shows featured collections

### ISSUE THREAD

**Issue by toobulkeh** [vaporware/parkland#6]
Probably needs an admin interface for marking collections as featured.

The admin can be any Super-User (role model)

**Comment by toobulkeh** [comment]
<img width="998" alt="screen shot 2015-07-14 at 9 30 48 pm" src="https://cloud.githubusercontent.com/assets/1342064/8688932/a4384d28-2a6f-11e5-9926-424b012ec587.png">

**Comment by hsidar** [comment]
I think I might be able to do this one. How would you like me to proceed?

**Comment by toobulkeh** [comment]
I already got this one @hsidar :) Thanks though!

**Comment by hsidar** [comment]
Agh! @toobulkeh It took me a week to build up the courage to raise my hand for this. So then, which issue can I be of assistance with?
