### ISSUE TITLE
Resources have more data behind them

### ISSUE THREAD

**Issue by toobulkeh** [vaporware/parkland#7]
Maybe a STI model where a resource can be a person or a company for starters.

**Comment by rjcox** [comment]
Added radio buttons to select "Person" or "Company" when creating new resource.  Added icon to left-most table cell for each resource on the resources index page.  Type is shown in resources show page as well.

**Comment by toobulkeh** [comment]
Nice, what about the separate data types? For example a person can have a company (not a separate resource) but maybe some company data to round it out a bit more?

**Comment by rjcox** [comment]
Resource tables now have organization, organization link, and organization description.

**Comment by rjcox** [comment]
Only able to add them if resource type is person.
